name: Build

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
      - README.md
  workflow_dispatch:

jobs:
  renderer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
        working-directory: ./renderer
      - run: npm run make-index-files
        working-directory: ./renderer
      - run: npm run lint
        working-directory: ./renderer
      - run: npm run build
        working-directory: ./renderer
      - uses: actions/upload-artifact@v4
        with:
          name: renderer-dist
          path: ./renderer/dist
          retention-days: 1

  package:
    needs: renderer
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/download-artifact@v4
        with:
          name: renderer-dist
          path: ./renderer/dist
      - run: npm ci
        working-directory: ./main
      - run: npm run build
        working-directory: ./main
      - run: npm run package "--" -p onTagOrDraft
        working-directory: ./main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Hash
        run: type .\main\dist\latest.yml
      - name: Separate Setup and other EXEs
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path setup_exe
          New-Item -ItemType Directory -Force -Path other_exes

          Get-ChildItem -Path .\main\dist\*.exe | ForEach-Object {
            if ($_.Name -like "*Setup*") {
              Copy-Item $_.FullName -Destination setup_exe
            } else {
              Copy-Item $_.FullName -Destination other_exes
            }
          }
      - name: Upload Setup EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-setup
          path: setup_exe
      - name: Upload Other EXEs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: other_exes
